fix platform010 build failure in ReproFXLib
Summary:
For platform010 build, this one is failing due to
```
glow/glow/tests/unittests/ReproFXLib.cpp:87:25: error: no matching member function for call to 'attr'
      currMod = currMod.attr(modName).toModule();
                ~~~~~~~~^~~~
caffe2/torch/csrc/jit/api/object.h:74:15: note: candidate function not viable: no known conversion from 'const llvm::StringRef' to 'const std::string' (aka 'const basic_string<char>') for 1st argument
  c10::IValue attr(const std::string& name) const {
              ^
caffe2/torch/csrc/jit/api/object.h:87:15: note: candidate function not viable: requires 2 arguments, but 1 was provided
  c10::IValue attr(const std::string& name, c10::IValue or_else) const {
              ^
glow/glow/tests/unittests/ReproFXLib.cpp:89:36: error: no matching member function for call to 'attr'
    torch::Tensor tensor = currMod.attr(modPathAndWeightName.second).toTensor();
                           ~~~~~~~~^~~~
caffe2/torch/csrc/jit/api/object.h:74:15: note: candidate function not viable: no known conversion from 'llvm::StringRef' to 'const std::string' (aka 'const basic_string<char>') for 1st argument
  c10::IValue attr(const std::string& name) const {
              ^
caffe2/torch/csrc/jit/api/object.h:87:15: note: candidate function not viable: requires 2 arguments, but 1 was provided
  c10::IValue attr(const std::string& name, c10::IValue or_else) const {
              ^
2 errors generated.
```

Differential Revision: D34410208

fbshipit-source-id: cbf339967638d1d7075aed7c2e4eeb63f935d8b3