Fix CI (#5654)
Summary:
Pull Request resolved: https://github.com/pytorch/glow/pull/5654

This is supposed to fix https://app.circleci.com/pipelines/github/pytorch/glow/13376/workflows/26f5cf38-8a69-40c6-b1cd-e6da5fc879e8/jobs/98138

```
+ ./utils/format.sh check
/usr/bin/clang-format
Running check format.
Ubuntu clang-format version 11.1.0-++20210314110124+1fdec59bffc1-1~exp1~20210314220751.162
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/venv/lib/python3.6/site-packages/black/__main__.py", line 3, in <module>
    patched_main()
  File "/tmp/venv/lib/python3.6/site-packages/black/__init__.py", line 6607, in patched_main
    main()
  File "/tmp/venv/lib/python3.6/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/click/core.py", line 1040, in main
    _verify_python_env()
  File "/tmp/venv/lib/python3.6/site-packages/click/_unicodefun.py", line 100, in _verify_python_env
    raise RuntimeError("\n\n".join(extra))
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

Exited with code exit status 1
```

Reviewed By: jfix71

Differential Revision: D28389676

fbshipit-source-id: 1d2cda45e6490f286989785d94f295ab9757f3fe