Fixing CI issues after changes in psf/black formatting utility (#5929)
Summary:
Pull Request resolved: https://github.com/pytorch/glow/pull/5929

## The problem
Earlier this week `black` formatting utility got broken https://github.com/psf/black/issues/2964.

An example stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/venv/lib/python3.9/site-packages/black/__main__.py", line 3, in <module>
    patched_main()
  File "/tmp/venv/lib/python3.9/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/tmp/venv/lib/python3.9/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/tmp/venv/lib/python3.9/site-packages/click/__init__.py)
```

Sample failed run https://app.circleci.com/pipelines/github/pytorch/glow/14399/workflows/db9175d4-6b03-4da1-8650-23001941a5a3/jobs/106452

## The solution
Seems that we have to update to version `22.3.0`. This change also required to upgrade some Python scripts from `python2` to `python3`.

Reviewed By: hl475

Differential Revision: D35149268

fbshipit-source-id: e6a3af9ae8ff56d9e1e2209f3535744f0b19f33e