Fixes for Visual Studio Windows build. (#4826)
Summary:
**Summary**
- Add missing headers when building with Visual Studio.
- Make the GlowError default constructor public to fix the following compile error signaled from HostManager.cpp(180):
```
F:\glow-vcc-build\installed\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\future(226): error C2248: 'glow::detail::GlowError::GlowError': cannot access protected member declared in class 'glow::detail::GlowError' [F:\glow-vcc-build\glow_build\lib\Runtime\HostManager\HostManager.vcxproj]
  F:\glow-vcc-build\glow\include\glow/Support/Error.h(416): note: see declaration of 'glow::detail::GlowError::GlowError'
  F:\glow-vcc-build\glow\include\glow/Support/Error.h(373): note: see declaration of 'glow::detail::GlowError'
  F:\glow-vcc-build\installed\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\future(1398): note: while compiling class template member function 'std::promise<glow::Error>::promise(void)'
  F:\glow-vcc-build\glow\lib\Runtime\HostManager\HostManager.cpp(180): note: see reference to function template instantiation 'std::promise<glow::Error>::promise(void)' being compiled
  F:\glow-vcc-build\glow\lib\Runtime\HostManager\HostManager.cpp(180): note: see reference to class template instantiation 'std::promise<glow::Error>' being compiled
```

Pull Request resolved: https://github.com/pytorch/glow/pull/4826

Reviewed By: jackm321

Differential Revision: D23365641

Pulled By: jfix71

fbshipit-source-id: 1d8353c1fd1fcbaae7c2b7d0d8e43c12150cf1a9